import { useState } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { useConfirmDialog } from "@/hooks/use-confirm-dialog";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useResidents } from "@/hooks/use-residents";
import { useStaff } from "@/hooks/use-staff";
import { format } from "date-fns";
import { ptBR } from "date-fns/locale";
import {
  DollarSign, FileText, Plus, TrendingUp, AlertCircle, CheckCircle2,
  Clock, User, Trash2, Pencil, Wallet
} from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import type { AccountPayable, Contract, MonthlyFee } from "@shared/schema";

type AccountPayableDetail = {
  id: number;
  status: string;
  title: string;
  category: string;
  referenceMonth: string | null;
  dueDate: string | Date | null;
  paidAt?: string | Date | null;
  paymentMethod?: string | null;
  notes?: string | null;
  amount: number;
  discount?: number | null;
  extra?: number | null;
  isAutoGenerated: boolean;
  staffId?: number | null;
  staffName?: string | null;
  periodStart?: string | null;
  periodEnd?: string | null;
  totalShifts: number;
  unitValue: number;
  calculatedTotal: number;
  shifts: Array<{
    id: number;
    date: string;
    startTime: string | Date;
    endTime: string | Date;
    shiftType: string;
    shiftTypeLabel?: string;
    notes?: string | null;
  }>;
};

const PLAN_LABELS: Record<string, string> = {
  standard: "Standard",
  premium: "Premium",
  vip: "VIP",
};

const STATUS_FEE: Record<string, { label: string; color: string; bg: string }> = {
  pending: { label: "Pendente", color: "#F59E0B", bg: "#FEF3C7" },
  paid: { label: "Pago", color: "#22C55E", bg: "#DCFCE7" },
  overdue: { label: "Em Atraso", color: "#EF4444", bg: "#FEE2E2" },
  cancelled: { label: "Cancelado", color: "#6B7280", bg: "#F3F4F6" },
};

const STATUS_CONTRACT: Record<string, { label: string; color: string }> = {
  active: { label: "Ativo", color: "#22C55E" },
  suspended: { label: "Suspenso", color: "#F59E0B" },
  terminated: { label: "Encerrado", color: "#EF4444" },
};

const PAYABLE_CATEGORY_LABELS: Record<string, string> = {
  staff: "Equipe/Cuidador",
  encargos: "Encargos",
  servicos: "Servicos",
  outros: "Outros",
};

const STATUS_PAYABLE: Record<string, { label: string; color: string; bg: string }> = {
  pending: { label: "Pendente", color: "#F59E0B", bg: "#FEF3C7" },
  paid: { label: "Pago", color: "#22C55E", bg: "#DCFCE7" },
  overdue: { label: "Em Atraso", color: "#EF4444", bg: "#FEE2E2" },
  cancelled: { label: "Cancelado", color: "#6B7280", bg: "#F3F4F6" },
};

const contractSchema = z.object({
  residentId: z.coerce.number().min(1, "Residente obrigatÃ³rio"),
  plan: z.enum(["standard", "premium", "vip"]),
  monthlyValue: z.coerce.number().min(1, "Valor obrigatÃ³rio"),
  startDate: z.string().min(1, "Data obrigatÃ³ria"),
  endDate: z.string().optional(),
  paymentDay: z.coerce.number().min(1).max(31).default(5),
  paymentMethod: z.string().optional(),
  notes: z.string().optional(),
});

const feeSchema = z.object({
  contractId: z.coerce.number().min(1, "Contrato obrigatÃ³rio"),
  residentId: z.coerce.number().min(1),
  referenceMonth: z.string().min(1, "MÃªs obrigatÃ³rio"),
  dueDate: z.string().min(1, "Vencimento obrigatÃ³rio"),
  amount: z.coerce.number().min(1, "Valor obrigatÃ³rio"),
  discount: z.coerce.number().default(0),
  fine: z.coerce.number().default(0),
  status: z.enum(["pending", "paid", "overdue", "cancelled"]).default("pending"),
  notes: z.string().optional(),
});

const payableSchema = z.object({
  title: z.string().min(2, "Descricao obrigatoria"),
  category: z.enum(["staff", "encargos", "servicos", "outros"]).default("staff"),
  staffId: z.coerce.number().optional().nullable(),
  referenceMonth: z.string().optional(),
  dueDate: z.string().min(1, "Vencimento obrigatorio"),
  amount: z.coerce.number().min(1, "Valor obrigatorio"),
  discount: z.coerce.number().default(0),
  extra: z.coerce.number().default(0),
  status: z.enum(["pending", "paid", "overdue", "cancelled"]).default("pending"),
  paymentMethod: z.string().optional(),
  notes: z.string().optional(),
});

function formatCurrency(value: number) {
  return new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(value);
}

function parseDateOnly(value: string | Date | null | undefined): Date | null {
  if (!value) return null;
  if (value instanceof Date) return value;
  if (/^\d{4}-\d{2}-\d{2}$/.test(value)) return new Date(`${value}T00:00:00`);
  const parsed = new Date(value);
  if (Number.isNaN(parsed.getTime())) return null;
  return parsed;
}

function parseDateTime(value: string | Date | null | undefined): Date | null {
  if (!value) return null;
  if (value instanceof Date) return value;
  const parsed = new Date(value);
  if (Number.isNaN(parsed.getTime())) return null;
  return parsed;
}

async function parseApiJson<T>(res: Response, fallbackMessage: string): Promise<T> {
  const contentType = (res.headers.get("content-type") || "").toLowerCase();
  const raw = await res.text();
  const trimmed = raw.trim();

  const looksLikeJson =
    contentType.includes("application/json")
    || trimmed.startsWith("{")
    || trimmed.startsWith("[");

  let data: unknown = null;
  if (trimmed.length > 0) {
    if (!looksLikeJson) {
      if (trimmed.startsWith("<!DOCTYPE") || trimmed.startsWith("<html")) {
        throw new Error("Resposta HTML recebida da API. Reinicie/atualize o backend e confira o proxy.");
      }
      throw new Error(fallbackMessage);
    }
    try {
      data = JSON.parse(trimmed);
    } catch {
      throw new Error("Resposta JSON invÃ¡lida da API.");
    }
  }

  if (!res.ok) {
    const message =
      typeof (data as { message?: unknown })?.message === "string"
        ? ((data as { message: string }).message.trim() || fallbackMessage)
        : fallbackMessage;
    throw new Error(message);
  }

  return data as T;
}

function KpiCard({ title, value, sub, icon: Icon, color }: any) {
  return (
    <div className="bg-card rounded-2xl border border-border/60 shadow-sm p-5">
      <div className="flex items-center justify-between mb-3">
        <p className="text-sm font-medium text-muted-foreground">{title}</p>
        <div className="h-9 w-9 rounded-xl flex items-center justify-center" style={{ background: `${color}18` }}>
          <Icon className="h-4 w-4" style={{ color }} />
        </div>
      </div>
      <p className="text-2xl font-bold text-foreground" style={{ fontFamily: "var(--font-display)" }}>{value}</p>
      {sub && <p className="text-xs text-muted-foreground mt-1">{sub}</p>}
    </div>
  );
}

export default function Financeiro() {
  const [contractOpen, setContractOpen] = useState(false);
  const [feeOpen, setFeeOpen] = useState(false);
  const [payableOpen, setPayableOpen] = useState(false);
  const [selectedPayableId, setSelectedPayableId] = useState<number | null>(null);
  const [editingContract, setEditingContract] = useState<(Contract & { residentName?: string }) | null>(null);
  const { toast } = useToast();
  const queryClient = useQueryClient();
  const { confirm, confirmDialog } = useConfirmDialog();
  const { data: residents = [] } = useResidents({ status: "active" });
  const { data: staff = [] } = useStaff();

  const { data: contracts = [], isLoading: contractsLoading } = useQuery<(Contract & { residentName?: string })[]>({
    queryKey: ["/api/contracts"],
    queryFn: async () => {
      const res = await fetch("/api/contracts", { credentials: "include" });
      return parseApiJson<(Contract & { residentName?: string })[]>(res, "Erro ao carregar contratos.");
    },
  });

  const { data: fees = [], isLoading: feesLoading } = useQuery<(MonthlyFee & { residentName?: string })[]>({
    queryKey: ["/api/monthly-fees"],
    queryFn: async () => {
      const res = await fetch("/api/monthly-fees", { credentials: "include" });
      return parseApiJson<(MonthlyFee & { residentName?: string })[]>(res, "Erro ao carregar mensalidades.");
    },
  });

  const { data: accountsPayable = [], isLoading: accountsPayableLoading } = useQuery<(AccountPayable & { staffName?: string })[]>({
    queryKey: ["/api/accounts-payable"],
    queryFn: async () => {
      const res = await fetch("/api/accounts-payable", { credentials: "include" });
      return parseApiJson<(AccountPayable & { staffName?: string })[]>(res, "Erro ao carregar contas a pagar.");
    },
  });

  const {
    data: payableDetails,
    isLoading: payableDetailsLoading,
    error: payableDetailsError,
  } = useQuery<AccountPayableDetail | null>({
    queryKey: ["/api/accounts-payable/details", selectedPayableId],
    enabled: selectedPayableId !== null,
    queryFn: async () => {
      if (selectedPayableId === null) return null;
      const res = await fetch(`/api/accounts-payable/${selectedPayableId}/details`, { credentials: "include" });
      return parseApiJson<AccountPayableDetail>(res, "Erro ao carregar detalhamento da conta a pagar.");
    },
  });

  const today = new Date();
  today.setHours(0, 0, 0, 0);

  function effectiveStatus(fee: any): string {
    if (fee.status === "pending" && fee.dueDate) {
      const due = parseDateOnly(fee.dueDate);
      if (due && due < today) return "overdue";
    }
    return fee.status;
  }

  function effectivePayableStatus(item: any): string {
    if (item.status === "pending" && item.dueDate) {
      const due = parseDateOnly(item.dueDate);
      if (due && due < today) return "overdue";
    }
    return item.status;
  }

  const totalPendingFees = fees.filter(f => effectiveStatus(f) === "pending").reduce((acc, f) => acc + (f.amount ?? 0), 0);
  const totalOverdue = fees.filter(f => effectiveStatus(f) === "overdue").reduce((acc, f) => acc + (f.amount ?? 0), 0);
  const totalReceived = fees.filter(f => f.status === "paid").reduce((acc, f) => acc + (f.amount ?? 0), 0);
  const activeContracts = contracts.filter(c => c.status === "active").length;
  const totalPendingPayables = accountsPayable
    .filter((item) => effectivePayableStatus(item) === "pending")
    .reduce((acc, item) => acc + (item.amount ?? 0) + (item.extra ?? 0) - (item.discount ?? 0), 0);
  const totalOverduePayables = accountsPayable
    .filter((item) => effectivePayableStatus(item) === "overdue")
    .reduce((acc, item) => acc + (item.amount ?? 0) + (item.extra ?? 0) - (item.discount ?? 0), 0);

  // Delete contract
  const deleteContract = useMutation({
    mutationFn: async (id: number) => {
      const res = await fetch(`/api/contracts/${id}`, { method: "DELETE", credentials: "include" });
      if (!res.ok) throw new Error("Erro ao excluir contrato");
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/contracts"] });
      toast({ title: "Contrato excluÃ­do" });
    },
    onError: () => toast({ variant: "destructive", title: "Erro ao excluir contrato" }),
  });

  // Update contract status
  const updateContractStatus = useMutation({
    mutationFn: async ({ id, status }: { id: number; status: string }) => {
      const res = await fetch(`/api/contracts/${id}`, {
        method: "PUT", credentials: "include",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ status }),
      });
      if (!res.ok) throw new Error("Erro ao atualizar contrato");
      return res.json();
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/contracts"] });
      setEditingContract(null);
      toast({ title: "Contrato atualizado" });
    },
    onError: () => toast({ variant: "destructive", title: "Erro ao atualizar contrato" }),
  });

  // Delete monthly fee
  const deleteMonthlyFee = useMutation({
    mutationFn: async (id: number) => {
      const res = await fetch(`/api/monthly-fees/${id}`, { method: "DELETE", credentials: "include" });
      if (!res.ok) throw new Error("Erro ao excluir cobranÃ§a");
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/monthly-fees"] });
      queryClient.invalidateQueries({ queryKey: ["/api/stats"] });
      toast({ title: "CobranÃ§a excluÃ­da" });
    },
    onError: () => toast({ variant: "destructive", title: "Erro ao excluir cobranÃ§a" }),
  });

  // Mark as paid
  const markPaid = useMutation({
    mutationFn: async (id: number) => {
      const res = await fetch(`/api/monthly-fees/${id}`, {
        method: "PUT", credentials: "include",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ status: "paid", paidAt: new Date().toISOString() }),
      });
      if (!res.ok) throw new Error("Erro");
      return res.json();
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/monthly-fees"] });
      queryClient.invalidateQueries({ queryKey: ["/api/stats"] });
      toast({ title: "Mensalidade registrada como paga" });
    },
  });

  const deleteAccountPayable = useMutation({
    mutationFn: async (id: number) => {
      const res = await fetch(`/api/accounts-payable/${id}`, { method: "DELETE", credentials: "include" });
      if (!res.ok) throw new Error("Erro ao excluir conta a pagar");
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/accounts-payable"] });
      queryClient.invalidateQueries({ queryKey: ["/api/accounts-payable/details"] });
      toast({ title: "Conta a pagar excluida" });
    },
    onError: () => toast({ variant: "destructive", title: "Erro ao excluir conta a pagar" }),
  });

  const markPayablePaid = useMutation({
    mutationFn: async (id: number) => {
      const res = await fetch(`/api/accounts-payable/${id}`, {
        method: "PUT", credentials: "include",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ status: "paid", paidAt: new Date().toISOString() }),
      });
      if (!res.ok) throw new Error("Erro ao registrar pagamento");
      return res.json();
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/accounts-payable"] });
      queryClient.invalidateQueries({ queryKey: ["/api/accounts-payable/details"] });
      toast({ title: "Pagamento registrado" });
    },
  });

  // Contract form
  const contractForm = useForm<z.infer<typeof contractSchema>>({
    resolver: zodResolver(contractSchema),
    defaultValues: { plan: "standard", paymentDay: 5, monthlyValue: 3200, startDate: new Date().toISOString().split("T")[0] },
  });

  const createContract = useMutation({
    mutationFn: async (data: z.infer<typeof contractSchema>) => {
      const res = await fetch("/api/contracts", {
        method: "POST", credentials: "include",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(data),
      });
      if (!res.ok) throw new Error("Erro");
      return res.json();
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/contracts"] });
      setContractOpen(false);
      contractForm.reset();
      toast({ title: "Contrato criado com sucesso" });
    },
    onError: () => toast({ variant: "destructive", title: "Erro ao criar contrato" }),
  });

  // Fee form
  const feeForm = useForm<z.infer<typeof feeSchema>>({
    resolver: zodResolver(feeSchema),
    defaultValues: { status: "pending", discount: 0, fine: 0 },
  });

  const createFee = useMutation({
    mutationFn: async (data: z.infer<typeof feeSchema>) => {
      const res = await fetch("/api/monthly-fees", {
        method: "POST", credentials: "include",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(data),
      });
      if (!res.ok) throw new Error("Erro");
      return res.json();
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/monthly-fees"] });
      setFeeOpen(false);
      feeForm.reset();
      toast({ title: "CobranÃ§a criada" });
    },
  });

  const payableForm = useForm<z.infer<typeof payableSchema>>({
    resolver: zodResolver(payableSchema),
    defaultValues: {
      title: "",
      category: "staff",
      staffId: undefined,
      referenceMonth: new Date().toISOString().slice(0, 7),
      dueDate: new Date().toISOString().split("T")[0],
      amount: 0,
      discount: 0,
      extra: 0,
      status: "pending",
      paymentMethod: "",
      notes: "",
    },
  });

  const createAccountPayable = useMutation({
    mutationFn: async (data: z.infer<typeof payableSchema>) => {
      const payload = {
        ...data,
        staffId: data.category === "staff" && data.staffId ? Number(data.staffId) : null,
        referenceMonth: data.referenceMonth?.trim() ? data.referenceMonth : null,
        paymentMethod: data.paymentMethod?.trim() ? data.paymentMethod : null,
        notes: data.notes?.trim() ? data.notes : null,
      };
      const res = await fetch("/api/accounts-payable", {
        method: "POST",
        credentials: "include",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
      });
      if (!res.ok) throw new Error("Erro");
      return res.json();
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/accounts-payable"] });
      setPayableOpen(false);
      payableForm.reset({
        title: "",
        category: "staff",
        staffId: undefined,
        referenceMonth: new Date().toISOString().slice(0, 7),
        dueDate: new Date().toISOString().split("T")[0],
        amount: 0,
        discount: 0,
        extra: 0,
        status: "pending",
        paymentMethod: "",
        notes: "",
      });
      toast({ title: "Conta a pagar criada" });
    },
    onError: () => toast({ variant: "destructive", title: "Erro ao criar conta a pagar" }),
  });

  const payableCategory = payableForm.watch("category");

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h1 className="text-3xl font-bold text-foreground" style={{ fontFamily: "var(--font-display)" }}>
            Financeiro
          </h1>
          <p className="text-muted-foreground mt-1">Contratos, mensalidades e contas a pagar da equipe</p>
        </div>
        <div className="flex gap-2">
          <Dialog open={contractOpen} onOpenChange={setContractOpen}>
            <DialogTrigger asChild>
              <Button variant="outline" size="sm" className="gap-2" data-testid="button-new-contract">
                <FileText className="h-4 w-4" />Novo Contrato
              </Button>
            </DialogTrigger>
            <DialogContent className="max-w-lg max-h-[90vh] overflow-y-auto">
              <DialogHeader><DialogTitle>Novo Contrato</DialogTitle></DialogHeader>
              <Form {...contractForm}>
                <form onSubmit={contractForm.handleSubmit((d) => createContract.mutate(d))} className="space-y-4">
                  <FormField control={contractForm.control} name="residentId" render={({ field }) => (
                    <FormItem>
                      <FormLabel>Residente *</FormLabel>
                      <Select onValueChange={(v) => field.onChange(Number(v))} value={field.value?.toString() ?? ""}>
                        <FormControl><SelectTrigger data-testid="select-contract-resident"><SelectValue placeholder="Selecionar residente" /></SelectTrigger></FormControl>
                        <SelectContent>
                          {residents.map((r: any) => (
                            <SelectItem key={r.id} value={r.id.toString()}>{r.name}</SelectItem>
                          ))}
                        </SelectContent>
                      </Select>
                      <FormMessage />
                    </FormItem>
                  )} />
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                    <FormField control={contractForm.control} name="plan" render={({ field }) => (
                      <FormItem>
                        <FormLabel>Plano *</FormLabel>
                        <Select onValueChange={field.onChange} defaultValue={field.value}>
                          <FormControl><SelectTrigger><SelectValue /></SelectTrigger></FormControl>
                          <SelectContent>
                            <SelectItem value="standard">Standard</SelectItem>
                            <SelectItem value="premium">Premium</SelectItem>
                            <SelectItem value="vip">VIP</SelectItem>
                          </SelectContent>
                        </Select>
                      </FormItem>
                    )} />
                    <FormField control={contractForm.control} name="monthlyValue" render={({ field }) => (
                      <FormItem>
                        <FormLabel>Valor Mensal (R$) *</FormLabel>
                        <FormControl><Input type="number" step="0.01" {...field} data-testid="input-monthly-value" /></FormControl>
                        <FormMessage />
                      </FormItem>
                    )} />
                  </div>
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                    <FormField control={contractForm.control} name="startDate" render={({ field }) => (
                      <FormItem>
                        <FormLabel>InÃ­cio *</FormLabel>
                        <FormControl><Input type="date" {...field} /></FormControl>
                        <FormMessage />
                      </FormItem>
                    )} />
                    <FormField control={contractForm.control} name="paymentDay" render={({ field }) => (
                      <FormItem>
                        <FormLabel>Dia Vencimento</FormLabel>
                        <FormControl><Input type="number" min={1} max={31} {...field} /></FormControl>
                      </FormItem>
                    )} />
                  </div>
                  <FormField control={contractForm.control} name="paymentMethod" render={({ field }) => (
                    <FormItem>
                      <FormLabel>Forma de Pagamento</FormLabel>
                      <Select onValueChange={field.onChange} value={field.value ?? ""}>
                        <FormControl><SelectTrigger><SelectValue placeholder="Selecionar" /></SelectTrigger></FormControl>
                        <SelectContent>
                          <SelectItem value="pix">PIX</SelectItem>
                          <SelectItem value="boleto">Boleto</SelectItem>
                          <SelectItem value="debito_automatico">DÃ©bito AutomÃ¡tico</SelectItem>
                          <SelectItem value="dinheiro">Dinheiro</SelectItem>
                          <SelectItem value="transferencia">TransferÃªncia</SelectItem>
                        </SelectContent>
                      </Select>
                    </FormItem>
                  )} />
                  <FormField control={contractForm.control} name="notes" render={({ field }) => (
                    <FormItem>
                      <FormLabel>ObservaÃ§Ãµes</FormLabel>
                      <FormControl><Textarea rows={2} {...field} /></FormControl>
                    </FormItem>
                  )} />
                  <div className="flex justify-end gap-2">
                    <Button type="button" variant="outline" onClick={() => setContractOpen(false)}>Cancelar</Button>
                    <Button type="submit" disabled={createContract.isPending}>Criar Contrato</Button>
                  </div>
                </form>
              </Form>
            </DialogContent>
          </Dialog>

          <Dialog open={feeOpen} onOpenChange={setFeeOpen}>
            <DialogTrigger asChild>
              <Button size="sm" className="gap-2 btn-glow" data-testid="button-new-fee">
                <Plus className="h-4 w-4" />Nova CobranÃ§a
              </Button>
            </DialogTrigger>
            <DialogContent className="max-w-lg">
              <DialogHeader><DialogTitle>LanÃ§ar Mensalidade</DialogTitle></DialogHeader>
              <Form {...feeForm}>
                <form onSubmit={feeForm.handleSubmit((d) => createFee.mutate(d))} className="space-y-4">
                  <FormField control={feeForm.control} name="contractId" render={({ field }) => (
                    <FormItem>
                      <FormLabel>Contrato *</FormLabel>
                      <Select onValueChange={(v) => {
                        field.onChange(Number(v));
                        const c = contracts.find(ct => ct.id === Number(v));
                        if (c) {
                          feeForm.setValue("residentId", c.residentId);
                          feeForm.setValue("amount", c.monthlyValue ?? 0);
                        }
                      }} value={field.value?.toString() ?? ""}>
                        <FormControl><SelectTrigger data-testid="select-fee-contract"><SelectValue placeholder="Selecionar contrato" /></SelectTrigger></FormControl>
                        <SelectContent>
                          {contracts.filter(c => c.status === "active").map((c) => (
                            <SelectItem key={c.id} value={c.id.toString()}>
                              {c.residentName} â€” {PLAN_LABELS[c.plan ?? "standard"]} ({formatCurrency(c.monthlyValue ?? 0)}/mÃªs)
                            </SelectItem>
                          ))}
                        </SelectContent>
                      </Select>
                      <FormMessage />
                    </FormItem>
                  )} />
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                    <FormField control={feeForm.control} name="referenceMonth" render={({ field }) => (
                      <FormItem>
                        <FormLabel>MÃªs ReferÃªncia *</FormLabel>
                        <FormControl><Input type="month" {...field} /></FormControl>
                        <FormMessage />
                      </FormItem>
                    )} />
                    <FormField control={feeForm.control} name="dueDate" render={({ field }) => (
                      <FormItem>
                        <FormLabel>Vencimento *</FormLabel>
                        <FormControl><Input type="date" {...field} /></FormControl>
                        <FormMessage />
                      </FormItem>
                    )} />
                  </div>
                  <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
                    <FormField control={feeForm.control} name="amount" render={({ field }) => (
                      <FormItem>
                        <FormLabel>Valor (R$)</FormLabel>
                        <FormControl><Input type="number" step="0.01" {...field} /></FormControl>
                        <FormMessage />
                      </FormItem>
                    )} />
                    <FormField control={feeForm.control} name="discount" render={({ field }) => (
                      <FormItem>
                        <FormLabel>Desconto</FormLabel>
                        <FormControl><Input type="number" step="0.01" {...field} /></FormControl>
                      </FormItem>
                    )} />
                    <FormField control={feeForm.control} name="fine" render={({ field }) => (
                      <FormItem>
                        <FormLabel>Multa</FormLabel>
                        <FormControl><Input type="number" step="0.01" {...field} /></FormControl>
                      </FormItem>
                    )} />
                  </div>
                  <FormField control={feeForm.control} name="notes" render={({ field }) => (
                    <FormItem>
                      <FormLabel>ObservaÃ§Ãµes</FormLabel>
                      <FormControl><Textarea rows={2} {...field} /></FormControl>
                    </FormItem>
                  )} />
                  <div className="flex justify-end gap-2">
                    <Button type="button" variant="outline" onClick={() => setFeeOpen(false)}>Cancelar</Button>
                    <Button type="submit" disabled={createFee.isPending}>LanÃ§ar</Button>
                  </div>
                </form>
              </Form>
            </DialogContent>
          </Dialog>

          <Dialog open={payableOpen} onOpenChange={setPayableOpen}>
            <DialogTrigger asChild>
              <Button size="sm" variant="outline" className="gap-2" data-testid="button-new-payable">
                <Wallet className="h-4 w-4" />Nova Conta a Pagar
              </Button>
            </DialogTrigger>
            <DialogContent className="max-w-lg max-h-[90vh] overflow-y-auto">
              <DialogHeader><DialogTitle>Nova Conta a Pagar</DialogTitle></DialogHeader>
              <Form {...payableForm}>
                <form onSubmit={payableForm.handleSubmit((d) => createAccountPayable.mutate(d))} className="space-y-4">
                  <FormField control={payableForm.control} name="title" render={({ field }) => (
                    <FormItem>
                      <FormLabel>Descricao *</FormLabel>
                      <FormControl><Input {...field} placeholder="Ex: Pagamento cuidadora abril/2026" data-testid="input-payable-title" /></FormControl>
                      <FormMessage />
                    </FormItem>
                  )} />
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                    <FormField control={payableForm.control} name="category" render={({ field }) => (
                      <FormItem>
                        <FormLabel>Categoria *</FormLabel>
                        <Select
                          onValueChange={(v) => {
                            field.onChange(v);
                            if (v !== "staff") payableForm.setValue("staffId", undefined);
                          }}
                          value={field.value}
                        >
                          <FormControl><SelectTrigger><SelectValue placeholder="Selecionar categoria" /></SelectTrigger></FormControl>
                          <SelectContent>
                            <SelectItem value="staff">Equipe/Cuidador</SelectItem>
                            <SelectItem value="encargos">Encargos</SelectItem>
                            <SelectItem value="servicos">Servicos</SelectItem>
                            <SelectItem value="outros">Outros</SelectItem>
                          </SelectContent>
                        </Select>
                        <FormMessage />
                      </FormItem>
                    )} />
                    <FormField control={payableForm.control} name="staffId" render={({ field }) => (
                      <FormItem>
                        <FormLabel>Colaborador</FormLabel>
                        <Select
                          onValueChange={(v) => field.onChange(v === "none" ? undefined : Number(v))}
                          value={field.value ? String(field.value) : "none"}
                          disabled={payableCategory !== "staff"}
                        >
                          <FormControl><SelectTrigger><SelectValue placeholder="Selecionar colaborador" /></SelectTrigger></FormControl>
                          <SelectContent>
                            <SelectItem value="none">Nao vincular</SelectItem>
                            {staff.filter((member: any) => member.active !== false).map((member: any) => (
                              <SelectItem key={member.id} value={String(member.id)}>{member.name}</SelectItem>
                            ))}
                          </SelectContent>
                        </Select>
                        <FormMessage />
                      </FormItem>
                    )} />
                  </div>
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                    <FormField control={payableForm.control} name="referenceMonth" render={({ field }) => (
                      <FormItem>
                        <FormLabel>Mes Referencia</FormLabel>
                        <FormControl><Input type="month" {...field} value={field.value ?? ""} /></FormControl>
                        <FormMessage />
                      </FormItem>
                    )} />
                    <FormField control={payableForm.control} name="dueDate" render={({ field }) => (
                      <FormItem>
                        <FormLabel>Vencimento *</FormLabel>
                        <FormControl><Input type="date" {...field} /></FormControl>
                        <FormMessage />
                      </FormItem>
                    )} />
                  </div>
                  <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
                    <FormField control={payableForm.control} name="amount" render={({ field }) => (
                      <FormItem>
                        <FormLabel>Valor (R$) *</FormLabel>
                        <FormControl><Input type="number" step="0.01" {...field} /></FormControl>
                        <FormMessage />
                      </FormItem>
                    )} />
                    <FormField control={payableForm.control} name="discount" render={({ field }) => (
                      <FormItem>
                        <FormLabel>Desconto</FormLabel>
                        <FormControl><Input type="number" step="0.01" {...field} /></FormControl>
                      </FormItem>
                    )} />
                    <FormField control={payableForm.control} name="extra" render={({ field }) => (
                      <FormItem>
                        <FormLabel>Adicional</FormLabel>
                        <FormControl><Input type="number" step="0.01" {...field} /></FormControl>
                      </FormItem>
                    )} />
                  </div>
                  <FormField control={payableForm.control} name="paymentMethod" render={({ field }) => (
                    <FormItem>
                      <FormLabel>Forma de Pagamento</FormLabel>
                      <Select onValueChange={field.onChange} value={field.value ?? ""}>
                        <FormControl><SelectTrigger><SelectValue placeholder="Selecionar" /></SelectTrigger></FormControl>
                        <SelectContent>
                          <SelectItem value="pix">PIX</SelectItem>
                          <SelectItem value="boleto">Boleto</SelectItem>
                          <SelectItem value="transferencia">Transferencia</SelectItem>
                          <SelectItem value="dinheiro">Dinheiro</SelectItem>
                          <SelectItem value="cartao">Cartao</SelectItem>
                        </SelectContent>
                      </Select>
                    </FormItem>
                  )} />
                  <FormField control={payableForm.control} name="notes" render={({ field }) => (
                    <FormItem>
                      <FormLabel>Observacoes</FormLabel>
                      <FormControl><Textarea rows={2} {...field} value={field.value ?? ""} /></FormControl>
                    </FormItem>
                  )} />
                  <div className="flex justify-end gap-2">
                    <Button type="button" variant="outline" onClick={() => setPayableOpen(false)}>Cancelar</Button>
                    <Button type="submit" disabled={createAccountPayable.isPending}>Criar Conta</Button>
                  </div>
                </form>
              </Form>
            </DialogContent>
          </Dialog>
        </div>
      </div>

      {/* KPIs */}
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6">
        <KpiCard title="Contratos Ativos" value={activeContracts} sub="residentes com contrato" icon={FileText} color="#1F6FEB" />
        <KpiCard title="A Receber" value={formatCurrency(totalPendingFees)} sub="mensalidades pendentes" icon={Clock} color="#F59E0B" />
        <KpiCard title="Em Atraso" value={formatCurrency(totalOverdue)} sub="requerem atenÃ§Ã£o" icon={AlertCircle} color="#EF4444" />
        <KpiCard title="Recebido" value={formatCurrency(totalReceived)} sub="histÃ³rico de pagamentos" icon={TrendingUp} color="#22C55E" />
        <KpiCard title="A Pagar" value={formatCurrency(totalPendingPayables)} sub="despesas pendentes" icon={Wallet} color="#F97316" />
        <KpiCard title="Atrasadas (Pagar)" value={formatCurrency(totalOverduePayables)} sub="contas vencidas" icon={AlertCircle} color="#DC2626" />
      </div>

      <Tabs defaultValue="fees">
        <TabsList>
          <TabsTrigger value="fees" data-testid="tab-fees">
            <DollarSign className="h-3.5 w-3.5 mr-1.5" />Mensalidades
          </TabsTrigger>
          <TabsTrigger value="accounts-payable" data-testid="tab-accounts-payable">
            <Wallet className="h-3.5 w-3.5 mr-1.5" />Contas a Pagar
          </TabsTrigger>
          <TabsTrigger value="contracts" data-testid="tab-contracts">
            <FileText className="h-3.5 w-3.5 mr-1.5" />Contratos
          </TabsTrigger>
        </TabsList>

        {/* FEES TAB */}
        <TabsContent value="fees" className="mt-4">
          {feesLoading ? (
            <div className="space-y-3">{[1,2,3].map(i => <div key={i} className="h-20 bg-muted rounded-2xl animate-pulse" />)}</div>
          ) : fees.length === 0 ? (
            <div className="text-center py-16 text-muted-foreground">
              <DollarSign className="h-12 w-12 text-muted-foreground/30 mx-auto mb-3" />
              <p>Nenhuma cobranÃ§a lanÃ§ada.</p>
            </div>
          ) : (
            <div className="space-y-3">
              {fees.map((fee: any) => {
                const eff = effectiveStatus(fee);
                const s = STATUS_FEE[eff] ?? { label: eff, color: "#888", bg: "#F3F4F6" };
                const total = (fee.amount ?? 0) + (fee.fine ?? 0) - (fee.discount ?? 0);
                const feeDueDate = parseDateOnly(fee.dueDate);
                return (
                  <div key={fee.id} className="bg-card border border-border/60 rounded-2xl p-4 shadow-sm flex flex-wrap items-center gap-4" data-testid={`fee-${fee.id}`}>
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2 mb-0.5">
                        <p className="font-semibold text-foreground text-sm">{fee.residentName}</p>
                        <Badge className="text-xs" style={{ background: s.bg, color: s.color, border: `1px solid ${s.color}30` }}>
                          {s.label}
                        </Badge>
                      </div>
                      <p className="text-xs text-muted-foreground">
                        ReferÃªncia: {fee.referenceMonth} Â· Vencimento: {feeDueDate ? format(feeDueDate, "dd/MM/yyyy", { locale: ptBR }) : "â€”"}
                      </p>
                      {fee.paidAt && (
                        <p className="text-xs text-green-600 mt-0.5">
                          Pago em {format(new Date(fee.paidAt), "dd/MM/yyyy", { locale: ptBR })}
                          {fee.paymentMethod && ` Â· ${fee.paymentMethod}`}
                        </p>
                      )}
                    </div>
                    <div className="text-right shrink-0">
                      <p className="text-lg font-bold text-foreground">{formatCurrency(total)}</p>
                      {(fee.discount ?? 0) > 0 && <p className="text-xs text-green-600">-{formatCurrency(fee.discount)} desconto</p>}
                      {(fee.fine ?? 0) > 0 && <p className="text-xs text-red-600">+{formatCurrency(fee.fine)} multa</p>}
                    </div>
                    <div className="flex items-center gap-2 shrink-0">
                      {(eff === "pending" || eff === "overdue") && (
                        <Button size="sm" variant="outline" className="gap-1.5 text-green-700 border-green-200 hover:bg-green-50"
                          onClick={() => markPaid.mutate(fee.id)}
                          disabled={markPaid.isPending}
                          data-testid={`button-pay-${fee.id}`}
                        >
                          <CheckCircle2 className="h-4 w-4" />Registrar Pagamento
                        </Button>
                      )}
                      <Button
                        size="sm" variant="ghost"
                        className="text-muted-foreground hover:text-destructive hover:bg-destructive/10 h-8 w-8 p-0"
                        disabled={deleteMonthlyFee.isPending}
                        onClick={() => {
                          confirm({
                            title: "Excluir cobranÃ§a",
                            description: `Excluir esta cobranÃ§a de ${fee.residentName}?`,
                            confirmText: "Excluir",
                            pendingText: "Excluindo...",
                            variant: "destructive",
                            onConfirm: () => deleteMonthlyFee.mutateAsync(fee.id),
                          });
                        }}
                        data-testid={`button-delete-fee-${fee.id}`}
                      >
                        <Trash2 className="h-4 w-4" />
                      </Button>
                    </div>
                  </div>
                );
              })}
            </div>
          )}
        </TabsContent>

        {/* ACCOUNTS PAYABLE TAB */}
        <TabsContent value="accounts-payable" className="mt-4">
          {accountsPayableLoading ? (
            <div className="space-y-3">{[1,2,3].map(i => <div key={i} className="h-20 bg-muted rounded-2xl animate-pulse" />)}</div>
          ) : accountsPayable.length === 0 ? (
            <div className="text-center py-16 text-muted-foreground">
              <Wallet className="h-12 w-12 text-muted-foreground/30 mx-auto mb-3" />
              <p>Nenhuma conta a pagar cadastrada.</p>
            </div>
          ) : (
            <div className="space-y-3">
              {accountsPayable.map((item: any) => {
                const eff = effectivePayableStatus(item);
                const s = STATUS_PAYABLE[eff] ?? { label: eff, color: "#888", bg: "#F3F4F6" };
                const total = (item.amount ?? 0) + (item.extra ?? 0) - (item.discount ?? 0);
                const dueDate = parseDateOnly(item.dueDate);
                return (
                  <div
                    key={item.id}
                    className="bg-card border border-border/60 rounded-2xl p-4 shadow-sm flex flex-wrap items-center gap-4 cursor-pointer hover:border-primary/40 transition-colors"
                    data-testid={`payable-${item.id}`}
                    role="button"
                    tabIndex={0}
                    onClick={() => setSelectedPayableId(item.id)}
                    onKeyDown={(event) => {
                      if (event.key === "Enter" || event.key === " ") {
                        event.preventDefault();
                        setSelectedPayableId(item.id);
                      }
                    }}
                  >
                    <div className="flex-1 min-w-0">
                      <div className="flex flex-wrap items-center gap-2 mb-0.5">
                        <p className="font-semibold text-foreground text-sm">{item.title}</p>
                        <Badge className="text-xs" style={{ background: s.bg, color: s.color, border: `1px solid ${s.color}30` }}>
                          {s.label}
                        </Badge>
                        <Badge variant="secondary" className="text-xs">
                          {PAYABLE_CATEGORY_LABELS[item.category ?? "outros"] ?? item.category}
                        </Badge>
                        {item.staffName && <Badge variant="outline" className="text-xs">{item.staffName}</Badge>}
                      </div>
                      <p className="text-xs text-muted-foreground">
                        ReferÃªncia: {item.referenceMonth || "â€”"} Â· Vencimento: {dueDate ? format(dueDate, "dd/MM/yyyy", { locale: ptBR }) : "â€”"}
                      </p>
                      {item.paidAt && (
                        <p className="text-xs text-green-600 mt-0.5">
                          Pago em {format(new Date(item.paidAt), "dd/MM/yyyy", { locale: ptBR })}
                          {item.paymentMethod && ` Â· ${item.paymentMethod}`}
                        </p>
                      )}
                    </div>
                    <div className="text-right shrink-0">
                      <p className="text-lg font-bold text-foreground">{formatCurrency(total)}</p>
                      {(item.discount ?? 0) > 0 && <p className="text-xs text-green-600">-{formatCurrency(item.discount)} desconto</p>}
                      {(item.extra ?? 0) > 0 && <p className="text-xs text-red-600">+{formatCurrency(item.extra)} adicional</p>}
                    </div>
                    <div className="flex items-center gap-2 shrink-0">
                      {(eff === "pending" || eff === "overdue") && (
                        <Button
                          size="sm"
                          variant="outline"
                          className="gap-1.5 text-green-700 border-green-200 hover:bg-green-50"
                          onClick={(event) => {
                            event.stopPropagation();
                            markPayablePaid.mutate(item.id);
                          }}
                          disabled={markPayablePaid.isPending}
                          data-testid={`button-pay-payable-${item.id}`}
                        >
                          <CheckCircle2 className="h-4 w-4" />Registrar Pagamento
                        </Button>
                      )}
                      <Button
                        size="sm"
                        variant="ghost"
                        className="h-8 px-2 text-muted-foreground hover:text-foreground"
                        onClick={(event) => {
                          event.stopPropagation();
                          setSelectedPayableId(item.id);
                        }}
                        data-testid={`button-details-payable-${item.id}`}
                      >
                        Detalhar
                      </Button>
                      <Button
                        size="sm"
                        variant="ghost"
                        className="text-muted-foreground hover:text-destructive hover:bg-destructive/10 h-8 w-8 p-0"
                        disabled={deleteAccountPayable.isPending}
                        onClick={(event) => {
                          event.stopPropagation();
                          confirm({
                            title: "Excluir conta a pagar",
                            description: `Excluir a conta "${item.title}"?`,
                            confirmText: "Excluir",
                            pendingText: "Excluindo...",
                            variant: "destructive",
                            onConfirm: () => deleteAccountPayable.mutateAsync(item.id),
                          });
                        }}
                        data-testid={`button-delete-payable-${item.id}`}
                      >
                        <Trash2 className="h-4 w-4" />
                      </Button>
                    </div>
                  </div>
                );
              })}
            </div>
          )}
        </TabsContent>

        {/* CONTRACTS TAB */}
        <TabsContent value="contracts" className="mt-4">
          {contractsLoading ? (
            <div className="space-y-3">{[1,2,3].map(i => <div key={i} className="h-20 bg-muted rounded-2xl animate-pulse" />)}</div>
          ) : contracts.length === 0 ? (
            <div className="text-center py-16 text-muted-foreground">
              <FileText className="h-12 w-12 text-muted-foreground/30 mx-auto mb-3" />
              <p>Nenhum contrato cadastrado.</p>
            </div>
          ) : (
            <div className="space-y-3">
              {contracts.map((c: any) => {
                const s = STATUS_CONTRACT[c.status] ?? { label: c.status, color: "#888" };
                return (
                  <div key={c.id} className="bg-card border border-border/60 rounded-2xl p-4 shadow-sm flex flex-wrap items-center gap-4" data-testid={`contract-${c.id}`}>
                    <div className="h-10 w-10 rounded-xl flex items-center justify-center shrink-0" style={{ background: "#1F6FEB18" }}>
                      <User className="h-4 w-4" style={{ color: "#1F6FEB" }} />
                    </div>
                    <div className="flex-1 min-w-0">
                      <div className="flex flex-wrap items-center gap-2 mb-0.5">
                        <p className="font-semibold text-foreground text-sm">{c.residentName}</p>
                        <Badge className="text-xs" style={{ color: s.color, border: `1px solid ${s.color}30`, background: `${s.color}10` }}>
                          {s.label}
                        </Badge>
                        <Badge variant="secondary" className="text-xs">{PLAN_LABELS[c.plan ?? "standard"]}</Badge>
                      </div>
                      <p className="text-xs text-muted-foreground">
                        Desde {c.startDate ? format(new Date(c.startDate + "T00:00:00"), "dd/MM/yyyy", { locale: ptBR }) : "â€”"}
                        {c.paymentDay && ` Â· Vence dia ${c.paymentDay}`}
                        {c.paymentMethod && ` Â· ${c.paymentMethod}`}
                      </p>
                      {c.notes && <p className="text-xs text-muted-foreground/70 mt-0.5 truncate">{c.notes}</p>}
                    </div>
                    <div className="text-right shrink-0">
                      <p className="text-xl font-bold text-foreground">{formatCurrency(c.monthlyValue ?? 0)}</p>
                      <p className="text-xs text-muted-foreground">por mÃªs</p>
                    </div>
                    <div className="flex items-center gap-1 shrink-0">
                      <Button
                        size="sm" variant="ghost"
                        className="h-8 w-8 p-0 text-muted-foreground hover:text-foreground"
                        onClick={() => setEditingContract(c)}
                        data-testid={`button-edit-contract-${c.id}`}
                      >
                        <Pencil className="h-4 w-4" />
                      </Button>
                      <Button
                        size="sm" variant="ghost"
                        className="h-8 w-8 p-0 text-muted-foreground hover:text-destructive hover:bg-destructive/10"
                        disabled={deleteContract.isPending}
                        onClick={() => {
                          confirm({
                            title: "Excluir contrato",
                            description: `Excluir contrato de ${c.residentName}? Esta aÃ§Ã£o nÃ£o pode ser desfeita.`,
                            confirmText: "Excluir",
                            pendingText: "Excluindo...",
                            variant: "destructive",
                            onConfirm: () => deleteContract.mutateAsync(c.id),
                          });
                        }}
                        data-testid={`button-delete-contract-${c.id}`}
                      >
                        <Trash2 className="h-4 w-4" />
                      </Button>
                    </div>
                  </div>
                );
              })}
            </div>
          )}
        </TabsContent>
      </Tabs>

      <Dialog open={selectedPayableId !== null} onOpenChange={(open) => { if (!open) setSelectedPayableId(null); }}>
        <DialogContent className="max-w-3xl max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>Detalhamento da Conta a Pagar</DialogTitle>
          </DialogHeader>
          {payableDetailsLoading ? (
            <div className="space-y-3">
              {[1, 2, 3, 4].map((row) => (
                <div key={row} className="h-12 rounded-xl bg-muted animate-pulse" />
              ))}
            </div>
          ) : payableDetailsError || !payableDetails ? (
            <div className="text-sm text-muted-foreground py-6">
              {payableDetailsError instanceof Error
                ? payableDetailsError.message
                : "Nao foi possivel carregar a memoria de calculo deste lancamento."}
            </div>
          ) : (
            <div className="space-y-5">
              <div className="flex flex-wrap items-center gap-2">
                <Badge className="text-xs" style={{
                  background: (STATUS_PAYABLE[payableDetails.status] ?? STATUS_PAYABLE.pending).bg,
                  color: (STATUS_PAYABLE[payableDetails.status] ?? STATUS_PAYABLE.pending).color,
                  border: `1px solid ${(STATUS_PAYABLE[payableDetails.status] ?? STATUS_PAYABLE.pending).color}30`,
                }}>
                  {(STATUS_PAYABLE[payableDetails.status] ?? { label: payableDetails.status }).label}
                </Badge>
                <Badge variant="secondary" className="text-xs">
                  {PAYABLE_CATEGORY_LABELS[payableDetails.category ?? "outros"] ?? payableDetails.category}
                </Badge>
                {payableDetails.isAutoGenerated && (
                  <Badge variant="outline" className="text-xs">Gerado automaticamente pela escala</Badge>
                )}
              </div>

              <div className="rounded-xl border border-border/60 p-4 space-y-4">
                <p className="text-sm font-semibold text-foreground">{payableDetails.title}</p>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-3 text-sm">
                  <div>
                    <p className="text-xs text-muted-foreground">Periodo de referencia</p>
                    <p className="font-medium">{payableDetails.referenceMonth || "â€”"}</p>
                  </div>
                  <div>
                    <p className="text-xs text-muted-foreground">Cuidador vinculado</p>
                    <p className="font-medium">{payableDetails.staffName || "Nao vinculado"}</p>
                  </div>
                  <div>
                    <p className="text-xs text-muted-foreground">Quantidade de plantoes</p>
                    <p className="font-medium">{payableDetails.totalShifts}</p>
                  </div>
                  <div>
                    <p className="text-xs text-muted-foreground">Valor unitario do plantao</p>
                    <p className="font-medium">{formatCurrency(payableDetails.unitValue || 0)}</p>
                  </div>
                  <div>
                    <p className="text-xs text-muted-foreground">Valor total apurado (memoria)</p>
                    <p className="font-medium">{formatCurrency(payableDetails.calculatedTotal || 0)}</p>
                  </div>
                  <div>
                    <p className="text-xs text-muted-foreground">Valor do lancamento financeiro</p>
                    <p className="font-medium">
                      {formatCurrency((payableDetails.amount ?? 0) + (payableDetails.extra ?? 0) - (payableDetails.discount ?? 0))}
                    </p>
                  </div>
                  <div>
                    <p className="text-xs text-muted-foreground">Vencimento</p>
                    <p className="font-medium">
                      {parseDateOnly(payableDetails.dueDate) ? format(parseDateOnly(payableDetails.dueDate) as Date, "dd/MM/yyyy", { locale: ptBR }) : "â€”"}
                    </p>
                  </div>
                  <div>
                    <p className="text-xs text-muted-foreground">Status financeiro</p>
                    <p className="font-medium">
                      {(STATUS_PAYABLE[payableDetails.status] ?? { label: payableDetails.status }).label}
                    </p>
                  </div>
                </div>
              </div>

              <div className="space-y-3">
                <p className="text-sm font-semibold text-foreground">Plantoes considerados no calculo</p>
                {payableDetails.shifts.length === 0 ? (
                  <div className="rounded-xl border border-dashed border-border p-4 text-sm text-muted-foreground">
                    Nao ha plantoes vinculados para este lancamento.
                  </div>
                ) : (
                  <div className="space-y-2">
                    {payableDetails.shifts.map((shift) => {
                      const startTime = parseDateTime(shift.startTime);
                      const endTime = parseDateTime(shift.endTime);
                      const day = parseDateOnly(shift.date);
                      const shiftNote = typeof shift.notes === "string"
                        ? shift.notes.replace(/^\[AUTO-MONTH:[^\]]+\]\s*/i, "")
                        : "";
                      return (
                        <div key={shift.id} className="rounded-xl border border-border/60 p-3">
                          <div className="flex flex-wrap items-center justify-between gap-2">
                            <p className="text-sm font-medium">
                              {day ? format(day, "dd/MM/yyyy", { locale: ptBR }) : shift.date}
                              {" â€” "}
                              {startTime ? format(startTime, "HH:mm") : "--:--"}
                              {" as "}
                              {endTime ? format(endTime, "HH:mm") : "--:--"}
                            </p>
                            <Badge variant="outline" className="text-xs">
                              {shift.shiftTypeLabel || shift.shiftType}
                            </Badge>
                          </div>
                          {shiftNote && (
                            <p className="text-xs text-muted-foreground mt-1">{shiftNote}</p>
                          )}
                        </div>
                      );
                    })}
                  </div>
                )}
              </div>

              {payableDetails.notes && (
                <div className="rounded-xl border border-border/60 p-3">
                  <p className="text-xs text-muted-foreground mb-1">Observacoes do lancamento</p>
                  <p className="text-sm text-foreground whitespace-pre-wrap break-words">{payableDetails.notes}</p>
                </div>
              )}
            </div>
          )}
        </DialogContent>
      </Dialog>

      {/* Edit contract status dialog */}
      <Dialog open={!!editingContract} onOpenChange={(o) => { if (!o) setEditingContract(null); }}>
        <DialogContent className="max-w-sm">
          <DialogHeader>
            <DialogTitle>Alterar Status do Contrato</DialogTitle>
          </DialogHeader>
          {editingContract && (
            <div className="space-y-4">
              <p className="text-sm text-muted-foreground">
                Contrato de <strong>{editingContract.residentName}</strong> â€” Plano {PLAN_LABELS[editingContract.plan ?? "standard"]}
              </p>
              <div className="space-y-2">
                {(["active", "suspended", "terminated"] as const).map((s) => (
                  <button
                    key={s}
                    type="button"
                    className={`w-full flex items-center gap-3 p-3 rounded-xl border text-sm font-medium transition-all ${
                      editingContract.status === s
                        ? "border-primary bg-primary/5 text-primary"
                        : "border-border hover:border-primary/50 text-foreground"
                    }`}
                    onClick={() => updateContractStatus.mutate({ id: editingContract.id, status: s })}
                    disabled={updateContractStatus.isPending}
                    data-testid={`contract-status-${s}`}
                  >
                    <span className="h-2.5 w-2.5 rounded-full shrink-0" style={{ background: STATUS_CONTRACT[s]?.color }} />
                    {STATUS_CONTRACT[s]?.label}
                    {editingContract.status === s && <span className="ml-auto text-xs text-primary">Atual</span>}
                  </button>
                ))}
              </div>
              <div className="flex justify-end">
                <Button variant="outline" size="sm" onClick={() => setEditingContract(null)}>Fechar</Button>
              </div>
            </div>
          )}
        </DialogContent>
      </Dialog>
      {confirmDialog}
    </div>
  );
}


